import { Injectable } from '@angular/core';
import { Food } from "../../shared/models/Food";
@Injectable({
  providedIn: 'root'
})
export class FoodService {

  constructor() { }

getFoodById(id: number):Food{

  return this.getAll().find(food => food.id == id)!;
}

  getAll():Food[]{
    return[
      {
        id: 1,
        name: 'Pizza Pepperoni',
        cookTime: '10-20',
        price: 'Rs.1000.00',
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: '/assets/images/foods/p1.png',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id: 2,
        name: 'Beef Burgers',
        cookTime: '10-20',
        price: 'Rs.800.00',
        favorite: false,
        origins: ['sriankan'],
        stars: 4.5,
        imageUrl: '/assets/images/foods/p2.png',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id: 3,
        name: 'Pizza Tomato',
        cookTime: '10-20',
        price: 'Rs.1000.00',
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: '/assets/images/foods/p3.png',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id: 4,
        name: 'Tomato Pasta',
        cookTime: '10-20',
        price: 'Rs.900.00',
        favorite: false,
        origins: ['indian'],
        stars: 4.5,
        imageUrl: '/assets/images/foods/p4.png',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id: 5,
        name: 'Cheese Burger',
        cookTime: '10-20',
        price: 'Rs.1100.00',
        favorite: false,
        origins: ['srilankan'],
        stars: 4.5,
        imageUrl: '/assets/images/foods/p5.png',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id: 6,
        name: 'Pizza Eggs',
        cookTime: '10-20',
        price: 'Rs.800.00',
        favorite: false,
        origins: ['srilankan'],
        stars: 4.5,
        imageUrl: '/assets/images/foods/p6.png',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id: 7,
        name: 'Pasta',
        cookTime: '10-20',
        price: 'Rs.800.00',
        favorite: false,
        origins: ['indian'],
        stars: 4.5,
        imageUrl: '/assets/images/foods/p7.png',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id: 8,
        name: 'Pizza Creamy',
        cookTime: '10-20',
        price: 'Rs.1300.00',
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: '/assets/images/foods/p8.png',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id: 9,
        name: 'Chiken Burger',
        cookTime: '10-20',
        price: 'Rs.750.00',
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: '/assets/images/foods/p9.png',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id: 10,
        name: 'Pizza with Chillies',
        cookTime: '10-20',
        price: 'Rs.1500.00',
        favorite: false,
        origins: ['indian'],
        stars: 4.5,
        imageUrl: '/assets/images/foods/p10.png',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id: 11,
        name: 'Pizza tomato cheese',
        cookTime: '10-20',
        price: 'Rs.1200.00',
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'assets/images/foods/p11.png',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id: 12,
        name: 'Pizza Normal',
        cookTime: '10-20',
        price: 'Rs.1000.00',
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: '/assets/images/foods/p12.png',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id: 13,
        name: 'Chiken Leg',
        cookTime: '10-20',
        price: 'Rs.800.00',
        favorite: false,
        origins: ['indian'],
        stars: 4.5,
        imageUrl: '/assets/images/foods/p13.png',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id: 14,
        name: 'Srilankan Traditionl Rice',
        cookTime: '10-20',
        price: 'Rs.2000.00',
        favorite: false,
        origins: ['srilankan'],
        stars: 4.5,
        imageUrl: '/assets/images/foods/p14.png',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
    ]
  }
}
